### ISSUE TITLE
Instance Arn missing on API calls

### ISSUE THREAD

**Issue by mmadaj** [aws-samples/aws-identitycenter-codepipeline-auto-assignment#10]
Missing required parameter in input: "InstanceArn" | [ERROR] 2023-08-21T23:34:24.352Z b42eda05-d40b-4cb7-ab9d-6a4a75c6034c Parameter validation failed: Missing required parameter in input: "InstanceArn"

Call on line 201 of auto-permissionsets.py needs "InstanceArn=ic_instance_arn"

Same with line 410 of auto-assignment.py.

This issue only occurs when results >100 for respective calls need to be iterated through.

**Comment by ashmeetp** [comment]
Thank you for reporting this issue. We are looking into it. You are also welcome to initiate a PR incase you get to the solution faster than we do.
